> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [4]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "maheshyv1999/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/maheshyv1999/numpy-array-operations


'https://jovian.ml/maheshyv1999/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [5]:
import numpy as np

In [ ]:
# List of functions explained 
function1 = np.split
function2 = np.reshape
function3 = np.insert
function3 = np.delete
function4 = np.append
function5 = np.unique

## Function 1 - np.split


Add some explanation about the function in your own words

In [12]:
x = np.arange(9.0) # creating array of 1 dimension
print(x)  # printing the 1 dimensional array
np.split(x, 3) #splitting the array with 3 indices, i.e 3 elements in one array

#split in 1 dimension takes 2 arguements as input array and split value and based on the value the array is splitted


[0. 1. 2. 3. 4. 5. 6. 7. 8.]


[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

Explanation about example

In [15]:
x = np.arange(8.0) #creating array of 1 dimension
print(x) # printing the 1 dimensional array
np.split(x, [3, 5, 6, 10])  #splitting the array with array and list as arguments,based on that 3 elements array,2 elements array
# 1 elements array,2 elements array are printed based on difference and number of elements in array

[0. 1. 2. 3. 4. 5. 6. 7.]


[array([0., 1., 2.]),
 array([3., 4.]),
 array([5.]),
 array([6., 7.]),
 array([], dtype=float64)]

Explanation about example

In [18]:

arr1 = [[1, 2],   # 2 dimensional array
        [3, 4.]]
np.split(arr1,2)  # condition that gives error


AttributeError: 'list' object has no attribute 'shape'

Explanation about example (why it breaks and how to fix it)

In [19]:
# above condition breaks because there is a missing of positional argument and no int type

np.array_split(arr1,2)  #it is splitted  row wise

[array([[1., 2.]]), array([[3., 4.]])]

Some closing comments about when to use this function.

In [20]:
#This function is used when there is need of separate the array and when the part of array is only required

In [21]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "maheshyv1999/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/maheshyv1999/numpy-array-operations


'https://jovian.ml/maheshyv1999/numpy-array-operations'

## Function 2 - np.reshape

Add some explanations

In [28]:
a=np.arange(9) # 1 dimension array creation
a.reshape((3,3))  #changing into 3 cross 3 matrix

#Gives a new shape to an array without changing its data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Explanation about example

In [33]:
a=np.arange(6)
np.reshape(a, (2, 3), order='F') # Fortran-like index ordering


array([[0, 2, 4],
       [1, 3, 5]])

Explanation about example

In [34]:
b=[[1,2,3],[5,6,7]]
np.reshape(b,3) #cannot reshape array of size 3 into shape

ValueError: cannot reshape array of size 6 into shape (3,)

Explanation about example (why it breaks and how to fix it)

In [35]:
#we need to pass 2 arguements that is row and column to work

b=[[1,2,3],[5,6,7]]
np.reshape(b,(3,2))

array([[1, 2],
       [3, 5],
       [6, 7]])

Some closing comments about when to use this function.

In [36]:
#it is used to change row to column and columns to row

In [37]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "maheshyv1999/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/maheshyv1999/numpy-array-operations


'https://jovian.ml/maheshyv1999/numpy-array-operations'

## Function 3 - np.insert

Add some explanations

In [39]:
a = np.array([[1, 1], [2, 2], [3, 3]]) # 3*3 array
print(a)
np.insert(a, 1, 5) #inserting 5 in 1st position

[[1 1]
 [2 2]
 [3 3]]


array([1, 5, 1, 2, 2, 3, 3])

Explanation about example

In [40]:
np.insert(a, [1], [[1],[2],[3]], axis=1)  # array with rows having same elements

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

Explanation about example

In [41]:
np.array_equal(np.insert(a, 1, [1, 2, 3], axis=1),
               np.insert(a, [1], [[1],[2],[3]], axis=1))# returns true or false

True

Explanation about example (why it breaks and how to fix it)

In [47]:
a = np.array([[1, 1], [2, 2] ,[3, 3]]) 
np.insert(a, 7, 5) # outer bound error

IndexError: index 7 is out of bounds for axis 0 with size 6

In [48]:
a = np.array([[1, 1], [2, 2] ,[3, 3]]) 
np.insert(a, 6, 5) # out of bound index is not possible

array([1, 1, 2, 2, 3, 3, 5])

Some closing comments about when to use this function.

In [49]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "maheshyv1999/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/maheshyv1999/numpy-array-operations


'https://jovian.ml/maheshyv1999/numpy-array-operations'

## Function 3 - np.delete

Add some explanations

In [50]:
#Return a new array with sub-arrays along an axis deleted. For a one dimensional array, this returns those entries not returned by arr[obj].
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)
np.delete(arr, 1, 0) #deleting the entire row of array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

Explanation about example

In [51]:
np.delete(arr, np.s_[::2], 1) # deleting 1st and 3rd col

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

Explanation about example

In [53]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)
np.delete(arr, 3, 5) #deleting 3rd col

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


AxisError: axis 5 is out of bounds for array of dimension 2

Explanation about example (why it breaks and how to fix it)

In [54]:
#out of bound error
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)
np.delete(arr, 2,1) #dont give out of bound values ,causes error

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 10, 12]])

Some closing comments about when to use this function.

In [55]:
#it si used to delete the unnecessary rows or columns

In [56]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "maheshyv1999/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/maheshyv1999/numpy-array-operations


'https://jovian.ml/maheshyv1999/numpy-array-operations'

## Function 4 - np.append

Add some explanations

In [57]:
np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]]) #Append values to the end of an array.

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Explanation about example

In [58]:
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0) # appending in 3 dimensions

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Explanation about example

In [59]:
np.append([[1, 2, 3], [4, 5, 6]], [7, 8, 9], axis=0) #all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Explanation about example (why it breaks and how to fix it)

In [63]:
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0) #using proper syntax ,all the input arrays must have same number of dimensions

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Some closing comments about when to use this function.

In [64]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "maheshyv1999/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/maheshyv1999/numpy-array-operations


'https://jovian.ml/maheshyv1999/numpy-array-operations'

## Function 5 - np.unique

Add some explanations

In [65]:
#Find the unique elements of an array.Returns the sorted unique elements of an array
np.unique([1, 1, 2, 2, 3, 3])#removing duplicates

array([1, 2, 3])

Explanation about example

In [66]:
a = np.array([[1, 1], [2, 3]]) #2 dimension
np.unique(a) # it removes the duplicates and converts to 1-d

array([1, 2, 3])

Explanation about example

In [72]:
a = np.array([[1, 0, 0], [1, 0, 0], [2, 3, 4]])
np.unique(a, 1)  #wrong arguements 

(array([0, 1, 2, 3, 4]), array([1, 0, 6, 7, 8], dtype=int64))

Explanation about example (why it breaks and how to fix it)

In [73]:
a = np.array([[1, 0, 0], [1, 0, 0], [2, 3, 4]])
np.unique(a, axis=1) #give proper arguements

array([[0, 0, 1],
       [0, 0, 1],
       [3, 4, 2]])

Some closing comments about when to use this function.

In [74]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "maheshyv1999/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/maheshyv1999/numpy-array-operations


'https://jovian.ml/maheshyv1999/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [75]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "maheshyv1999/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/maheshyv1999/numpy-array-operations


'https://jovian.ml/maheshyv1999/numpy-array-operations'